version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: react-dnd-html5-backend
    versions:
    - 11.1.3
    - 12.0.0
    - 12.1.0
    - 12.1.1
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.13.0
    - 7.13.5
  - dependency-name: whatwg-fetch
    versions:
    - 3.5.0
    - 3.6.1
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
